# Generated by Django 5.1 on 2024-08-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotteryhis',
            name='create_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lotteryhis',
            name='next_opentime',
            field=models.DateTimeField(),
        ),
    ]
