# Generated by Django 5.1 on 2024-08-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='girl',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='girl',
            name='update_time',
        ),
    ]
