# Generated by Django 5.1 on 2024-08-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_remove_girl_create_time_remove_girl_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotteryedit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
