# Generated by Django 5.1 on 2024-08-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_lotteryedit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
