# Generated by Django 5.1 on 2024-08-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_member_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='desc',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawallist',
            name='desc',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
